In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('airbnb.csv')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10019 entries, 0 to 10018
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          10019 non-null  int64
 1   listing_id          10019 non-null  int64
 2   name                10014 non-null  str
 3   host_id             10019 non-null  int64
 4   host_name           10017 non-null  str
 5   neighbourhood_full  10019 non-null  str
 6   coordinates         10019 non-null  str
 7   room_type           10019 non-null  str
 8   price               9781 non-null   str
 9   number_of_reviews   10019 non-null  int64
 10  last_review         7944 non-null   str
 11  reviews_per_month   7944 non-null   float64
 12  availability_365    10019 non-null  int64
 13  rating              7944 non-null   float64
 14  number_of_stays     7944 non-null   float64
 15  5_stars             7944 non-null   float64
 16  listing_added       10019 non-null  str
dtypes: float64(4), int64(5), str(8)
memory usage: 1.3 MB

In [6]:
df.head(10)

,Unnamed: 0,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added
0,0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","(40.63222, -73.93398)",Private room,45$,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08
1,1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","(40.78761, -73.96862)",Entire home/apt,135$,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25
2,2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights","(40.7007, -73.99517)",Entire home/apt,150$,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15
3,3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side","(40.79169, -73.97498)",Entire home/apt,86$,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20
4,4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side","(40.71884, -73.98354)",Private room,160$,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23
5,5,271954,Beautiful brownstone apartment,1423798,Aj,"Manhattan, Greenwich Village","(40.73388, -73.99452)",Entire home/apt,150$,203,2019-06-20,2.22,300,4.478396,243.6,0.743500,2018-12-15
6,6,33473567,Hamilton Heights Full Floor Garden Apt,33388853,Christine,"Manhattan, Harlem","(40.8309, -73.94308000000002)",Entire home/apt,200$,0,NaN,NaN,219,NaN,NaN,NaN,2018-05-05
7,7,14218742,Luxury/3bedroom/3bthrm/Privateprkng/beach/rstrnts,78824908,Ilona,"Brooklyn, Sheepshead Bay","(40.58531, -73.93811)",Entire home/apt,224$,2,2018-06-22,0.08,353,4.091228,2.4,0.690393,2017-12-17
8,8,15125599,Beautiful One Bedroom Apartment Near Central Park,3191545,Kyle,"Manhattan, Theater District","(40.761, -73.98522)",Entire home/apt,169$,5,2017-06-25,0.15,365,3.562947,6.0,0.704538,2016-12-20
9,9,24553891,Enjoy all of Manhattan. Big Apple! A Mini-MOMA!,68557372,Shannon,"Manhattan, Harlem","(40.80667, -73.95182)",Entire home/apt,75$,8,2019-04-24,0.66,9,4.695769,9.6,0.750073,2018-10-19

In [7]:
df.describe()

,Unnamed: 0,listing_id,host_id,number_of_reviews,reviews_per_month,availability_365,rating,number_of_stays,5_stars
count,10019.000000,1.001900e+04,1.001900e+04,10019.000000,7944.000000,10019.000000,7944.000000,7944.000000,7944.000000
mean,5009.000000,1.927634e+07,6.795923e+07,22.459727,1.353894,112.284260,4.014458,33.991541,0.718599
std,2892.380507,1.095056e+07,7.863106e+07,43.173896,1.615380,131.636043,0.575064,56.089279,0.079978
min,0.000000,3.831000e+03,2.787000e+03,0.000000,0.010000,0.000000,3.000633,1.200000,0.600026
25%,2504.500000,9.674772e+06,7.910880e+06,1.000000,0.200000,0.000000,3.520443,3.600000,0.655576
50%,5009.000000,2.007030e+07,3.165167e+07,5.000000,0.710000,44.000000,4.027965,10.800000,0.709768
75%,7513.500000,2.933864e+07,1.074344e+08,22.000000,2.000000,226.000000,4.516378,38.400000,0.763978
max,10018.000000,3.648724e+07,2.741034e+08,510.000000,16.220000,365.000000,5.181114,612.000000,0.950339

In [8]:
df.isna().sum()

Unnamed: 0               0
listing_id               0
name                     5
host_id                  0
host_name                2
neighbourhood_full       0
coordinates              0
room_type                0
price                  238
number_of_reviews        0
last_review           2075
reviews_per_month     2075
availability_365         0
rating                2075
number_of_stays       2075
5_stars               2075
listing_added            0
dtype: int64

In [11]:
df.dtypes

Unnamed: 0              int64
listing_id              int64
name                      str
host_id                 int64
host_name                 str
neighbourhood_full        str
coordinates               str
room_type                 str
price                     str
number_of_reviews       int64
last_review               str
reviews_per_month     float64
availability_365        int64
rating                float64
number_of_stays       float64
5_stars               float64
listing_added             str
dtype: object

In [ ]:
df['room_type'].unique()
# private room is written in different ways, we need to clean it up

<StringArray>
[        'Private room',      'Entire home/apt',              'Private',
          'Shared room',         'PRIVATE ROOM',                 'home',
 '   Shared room      ']
Length: 7, dtype: str

In [14]:
df['room_type'].value_counts()

room_type
Entire home/apt         5120
Private room            4487
Shared room              155
Private                   89
   Shared room            71
home                      66
PRIVATE ROOM              31
Name: count, dtype: int64

In [ ]:
df.price.head(10)
# price is a string (bc of the $), we need to convert it to a number

0     45$
1    135$
2    150$
3     86$
4    160$
5    150$
6    200$
7    224$
8    169$
9     75$
Name: price, dtype: str

In [17]:
#df['price'] = df['price'].str.replace('$', '').astype(float)
df['price'] = df['price'].str.strip('$')
df.price.head(5)

0     45
1    135
2    150
3     86
4    160
Name: price, dtype: str

In [ ]:
#df = df.astype({'price': 'float'})
df['price'] = df['price'].astype(float)
df.dtypes

Unnamed: 0              int64
listing_id              int64
name                      str
host_id                 int64
host_name                 str
neighbourhood_full        str
coordinates               str
room_type                 str
price                 float64
number_of_reviews       int64
last_review               str
reviews_per_month     float64
availability_365        int64
rating                float64
number_of_stays       float64
5_stars               float64
listing_added             str
dtype: object

In [23]:
avg = df.price.mean()

In [24]:
df['price'] = df['price'].fillna(avg)
df.isna().sum()

Unnamed: 0               0
listing_id               0
name                     5
host_id                  0
host_name                2
neighbourhood_full       0
coordinates              0
room_type                0
price                    0
number_of_reviews        0
last_review           2075
reviews_per_month     2075
availability_365         0
rating                2075
number_of_stays       2075
5_stars               2075
listing_added            0
dtype: int64